# Generated by Django 6.0.7 on 2026-08-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_instructorprofile_user_and_more'),
        ('sponsorships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='accounts.studentprofile'),
        ),
    ]
