# Generated by Django 6.0.7 on 2026-08-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_ASSESSMENT', 'New Assessment'), ('ASSESSMENT_DUE', 'Assessment Due'), ('ASSESSMENT_RESULT', 'Assessment Result'), ('COURSE_PROGRESS', 'Course Progress')], max_length=30),
        ),
    ]
